- name : PLAYBOOK variable
  hosts : localhost
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name : person
  #   prompt : please enter your name
  #   private : false
  # - name : wishes
  #   prompt : please enter your wishes
  #   private : false
  # vars :
  #   person: "chandu from play"
  #   wishes: "good morning from play"
  tasks:
  - name : check varaiables
  #   vars:
  #     person: "chandu from task"
  #     wishes: "good morning from task"
    ansible.builtin.debug:
      msg : "Hello {{person}}, Good {{wishes}}" 

      # 1. command line level
      # 2. task level
      # 3. from files
      # 4. prompt
      # 5. vars
      # 6. inventory
      # 7. roles