- name : PLAYBOOK variable
  hosts : localhost
  vars_files:
    - variables-1.yaml
  vars_prompt:
  - name : person
    prompt : please enter your name
    private : false
  - name : wishes
    prompt : please enter your wishes
    private : false
  vars :
    person:"chandu from play"
    wishes:"good morning from play"
  tasks:
  - name : check varaiable
    vars:
      person:"chandu from task"
      wishes:"good morning from task"
    ansible.builtin.debug:
      msg : "Hello {{person}},Good {{wishes}}" 