- name : install packages
  hosts : localhost
  become : yes
  tasks :
  - name : print packages
    ansible.builtin.package :
      name : "{{item}}"
      state : present
    loop : 
    - git
    - mysql
    - postfix